### ISSUE TITLE
candle examples fail on cuda with CUDA_DEVICE_NO_ERROR. Device caps of 7.5 

### ISSUE THREAD

**Issue by vamsi-juvvi** [huggingface/candle#2282]
**Environment**
 I am running on *Ubuntu 20.04 on WSL2* (Windows 11 host) and having trouble with candle on cuda. Cuda installation seems ok.  Everything builds but has a runtime failure.
 
**cargo run**
```bash
$cargo run --example bert --release --features cuda,cudnn -- --prompt "Here is a test sentence"
   Compiling candle-kernels v0.6.0 (/home/vamsi/github/candle/candle-kernels)
   Compiling candle-examples v0.6.0 (/home/vamsi/github/candle/candle-examples)
   Compiling candle-core v0.6.0 (/home/vamsi/github/candle/candle-core)
    ....
   Compiling candle-nn v0.6.0 (/home/vamsi/github/candle/candle-nn)
   Compiling candle-transformers v0.6.0 (/home/vamsi/github/candle/candle-transformers)
   Finished release [optimized] target(s) in 20.47s
   Running `target/release/examples/bert --prompt 'Here is a test sentence'`
🛑 Error: DriverError(CUDA_ERROR_NO_DEVICE, "no CUDA-capable device is detected")
```

👉 pytorch installation shows cuda/gpu and jupyter runs pytorch code with acceleration (Can see GPU load on taskmanager)

I nuked all cuda and nvidia packages via `sudo apt remove --purge` and reinstalled per nvidia's special WSL instructions at https://docs.nvidia.com/cuda/wsl-user-guide/index.html.

**nvidia-smi output**
```bash
$nvidia-smi --query-gpu=name,compute_cap,driver_version --format=csv
name, compute_cap, driver_version
NVIDIA GeForce RTX 2080 Ti, 7.5, 551.86
```

**nvcc** output
```bash
$nvcc --version
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2024 NVIDIA Corporation
Built on Wed_Apr_17_19:19:55_PDT_2024
Cuda compilation tools, release 12.5, V12.5.40
Build cuda_12.5.r12.5/compiler.34177558_0
```

relevant env vars (_also have `/usr/local/cuda-12.5` on PATH and LD_LBRARY_PATHS_)
```bash
CUDA_VISIBLE_DEVICES=0
CUDA_PATH=/usr/local/cuda-12.5
```

Listing nvidia's instructions for WSL2 cuda here in case it helps clarify the situation. The main idea is to avoid a driver install (_since there is a special libcuda.so that stubs for the actual driver on the windows host_). They recommend either a special meta package or a custom wsl-ubuntu one (_which is what I used here_). cudnn is installed later on as usual,

```bash
sudo apt-key del 7fa2af80
wget https://developer.download.nvidia.com/compute/cuda/repos/wsl-ubuntu/x86_64/cuda-wsl-ubuntu.pin
sudo mv cuda-wsl-ubuntu.pin /etc/apt/preferences.d/cuda-repository-pin-600
wget https://developer.download.nvidia.com/compute/cuda/12.5.0/local_installers/cuda-repo-wsl-ubuntu-12-5-local_12.5.0-1_amd64.deb
sudo dpkg -i cuda-repo-wsl-ubuntu-12-5-local_12.5.0-1_amd64.deb
sudo cp /var/cuda-repo-wsl-ubuntu-12-5-local/cuda-*-keyring.gpg /usr/share/keyrings/
sudo apt-get update
sudo apt-get -y install cuda-toolkit-12-5
```

Per other comments I gather that device caps of 7.5 (2080Ti) should be fine. I am hoping this is a subtle cuda installation issue. I can debug into the rust code if I get some pointers on where to look.

Would appreciate any help. Thanks!

**Comment by vamsi-juvvi** [comment]
Decided to try a fresh WSL environment instead of digging into `cudarc::driver` (_which candle_core::Device::new_cuda(x)` uses.

Some of the peculiarities and gotchas of WSL instrallation became clear and I found a fix for my issues. This is what I learnt.

NVidia instructions for WSL are very clear but I did not fully understand how straying from their instructions break your cuda installation.
 - `nvcc -V` works
 - `nvidia-smi --query-gpu=name,compute_cap,driver_version --format=csv` shows caps of 7.5 (2080Ti)
 - Runtime fails with **no CUDA capable devices**.
 - What gives ?

When you have a NVidia GPU on your windows host, an Ubuntu installation on WSL comes with 
 - `/usr/lib/wsl/lib/nvidia-smi` 
 - `/usr/lib/wsl/lib/libcuda.so.1`  _and others_

The way you arrive at the problem above is if you install a cuda package which installs another `libcuda.so`. The `/usr/lib/wsl/lib/libcuda.so` is a stub for the actual windows driver. Any other installed `libcuda.so` is disconnected from the underlying device and fails on use.

**Comment by vamsi-juvvi** [comment]
If you have gotten into a situation like mine, the fix is simply to ensure that `/usr/lib/wsl/lib` is placed early/front in your LD_LIBRARY_PATH.

Glorious to see the quantized llama2 example give me 50 tok/s compared to my CPU of 1.9 tok/s!
