### ISSUE TITLE
CudNN Support on FLUX?

### ISSUE THREAD

**Issue by super-fun-surf** [huggingface/candle#2534]
Running Flux example on A100 works great with feature "cuda" enabled. 

When "cudnn" feature is also enabled, it crashes with error:
```
Err(Wrapped(Wrapped(CudnnError(CUDNN_STATUS_BAD_PARAM))))
```
nvidia-smi
```
NVIDIA-SMI 535.129.03             Driver Version: 535.129.03   CUDA Version: 12.2     |
NVIDIA A100-SXM4-80GB
```

**Comment by LaurentMazare** [comment]
Thanks for reporting, this should be fixed in #2535 , in a nutshell the issue was that there is no `TRUE_BFLOAT16_CONFIG` supported by cudnn [convforward](https://docs.nvidia.com/deeplearning/cudnn/latest/api/cudnn-cnn-library.html#id88), I've switched it to use the `PSEUDO_BFLOAT16_CONFIG` and it works well on an H100.

**Comment by super-fun-surf** [comment]
Rad.  I can confirm its working on the A100 now.
thanks!
